= European Climate Declaration  September 26, 2019
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

toc::[]

== SCIENTISTS AND PROFESSIONALS FROM EU

=== SCIENTISTS AND PROFESSIONALS FROM BELGIUM

1.    Rob Lemeire, Publicist on Environmental and Climate Issues, ECD Ambassador
2.    Eric Blondeel, retired Civil Engineer.
3.    Emiel van Broekhoven, Emeritus Professor of Economics, University of Antwerp
4.    Christophe de Brouwer, MD, Honorary Professor of Environmental and Industrial Toxicology, Former President of the School of Public Health at the Université Libre de Bruxelles
5.    Christian Dierick, Lead Expert, Energy Technology Solutions
6.    Ferdinand Engelbeen, Former chemical process automation engineer, Akzo Nobel Chemicals
7.    Samuel Furfari, Professor of Energy Geopolitics at the Free University of Brussels
8.    Georges Geuskens, Emertitus Professor of Chemistry, Free University of Brussels and Expert Publicist on Climate Science
9.    Drieu Godefridi, PhD in Law, author of several books
10.   Jan Jacobs, Science Journalist Specializing in Climate and Energy Transition
11.   Raymond Koch, Retired Research director at Lab. Plasma Physics, RMA Brussels and Fellow Lecturer at UMons.
12.   Henri A. Masson, Emeritus Professor Dynamic System Analysis and Data Mining, University of Antwerp
13.   Ferdinand Meeus, Retired Research Scientist, IPCC expert Reviewer AR6
14.   Jean Meeus, Retired Meteorologist, Brussels Airport, Author of the Best Seller Astronomical Algorithms
15.   Ernest Mund, Honorary Research Director, FNRS, Nuclear Engineering
16.   Bart Ooghe, Geologist & Geophysicist, Independent Scientist
17.   Jozef Verhulst, Author
18.   Jean van Vliet, Retired Specialist in Space Weather
19.   Appo van der Wiel, Senior Development Engineer


=== SCIENTISTS AND PROFESSIONALS FROM CZECH REPUBLIC

1.    Václav Klaus, Former President of the Czech Republic, Professor of Economics, Founder of the Václav Klaus Institute


=== SCIENTISTS AND PROFESSIONALS FROM DENMARK

1.    Bjarne Andresen, Professor of Physics, Niels Bohr Institute, University of Copenhagen
2.    Peter Kjær Poulsen, Metering engineer, Denmark
3.    Johannes Krüger, Emeritus Professor, dr.scient, Department of Geosciences and Natural Resource Management, University of Copenhagen
4.    Niels Schrøder, Geophysist/Geologist, Associate Professor Institute of Nature and Environment, Roskilde University, Denmark


=== SCIENTISTS AND PROFESSIONALS FROM FRANCE

1.    Benoît Rittaud, Associate professor of Mathematics at University of Paris-Nord, President of the French Association des climato-réalistes. ECD Ambassador
2.    Jean-Charles Abbé, former research director at CNRS, labs director (Strasbourg, Nantes) in Radiochemistry, expert at NATO and IAEA
3.    Bertrand Aliot, Environmentalist
4.    Charles Aubourg, full professor at the University of Pau, geophysicist.
5.    Hervé Azoulay, Engineer (CNAM), Specialist of Networks and Systemics, External Speaker at Universities (France, Switzerland, China), CEO and President of several Associations
6.    Jean-Pierre Bardinet, Ingénieur ENSEM, publicist on climate issues
7.    Bernard Beauzamy, university professor (ret.), chairman and CEO, Société de Calcul Mathématique SA (Paris).
8.    Jean-Claude Bernier, emeritus professor (university of Strasbourg), former director of the Institute of Chemistry of the CNRS.
9.    Pierre Beslu, former searcher and head of department in the french Nuclear Energy Commission (CEA).
10.   Michel Bouillet, PhD Human Geography, Emeritus Professor, Former Associate Researcher at the MMSH (Aix-en-Provence)
11.   Christian Buson, PhD in agronomy, director of research in a company (impact studies in environmental issues, sewage treatment).
12.   Sylvie Brunel, full professor at Sorbonne University, geographer and economist, former president of the humanitarian organization Action against Hunger (Action contre la faim).
13.   Jean-Louis Butré, professional engineer, head of laboratory at Grenoble Nuclear Research Center, Chief executive officer or the Pharmacie Centrale de France, President of Axens, President of the Fédération Environnement Durable and the European Platform Against Windfarms, Knight of the National Order of Merit.
14.   Bernard Capai, Retired Chemistry Engineer, Specialist of Industrial Processes avoiding the use of carcinogenic solvents
15.   Patrick de Casanove, Doctor of Medicine, Chairman of the Cercle Frédéric Bastiat
16.   Philippe Catier, Medical Doctor
17.   Pascal Chondroyannis, Forest Engineer, Retired Director of the National Alpine Botanical Conservatory (2008-2013)
18.   Philippe Colomban, CNRS Research Professor, Former Head of Laboratory at Université Piere-et-Marie Curie, Expert in Hydrogen-based Energy Storage
19.   Jacques Colombani, Former Research Director retired from ORSTOM-IRD, numerous Studies in Hydrology and Climatology and Specialist in Fluid Mechanics. Member of the Board of ORSTOM for twenty years.
20.   Vincent Courtillot, geophysicist, member of the French Academy of Sciences, former director of the Institute de Physique du Globe de Paris
21.   Pierre Darriulat, Professor of Physics, Member of the French Academy of Sciences
22.   Gérard Douet, PhD in Nuclear Physics, Retired Engineer at CERN, Technical Manager on Digital Transmission and Video Encoding
23.   Hubert Dulieu, Emeritus Professor Applied Ecology, Formerly Senior Researcher in the CNRS, President of the National Scientific Research Committee, Vegetal Biology Section (XXVII)
24.   Bruno Durieux, economist, former Minister of Health and of Foreign Trade, ancient administrator of the French National Institute of Statistics and Economic Studies (INSEE).
25.   Max Falque, International Consultant in Environmental Policy
26.   Patrick Fischer, Associate Professor in Applied Mathematics, University of Bordeaux
27.   François Gauchenot, governance specialist, founder of Saint George Institute.
28.   Christian Gérondeau, former advisor of several French Prime Ministers. Former responsible for the road traffic safety policy for France and the European Union.
29.   Francois Gervais, Emeritus Professor of Physics and Material Sciences, University of Tours.
30.   Philippe Giraudin, Ecole Polytechnique Paris, Geographic Sciences
31.   Bernard Grandchamp, Agronomic Engineer and Environment & Plant Defense Expert, Managing Director of Famoux Chateaux Viticoles in Bordeaux
32.   Gilles Granereau, Former meteorologist, currently project manager environment and tourism in a public institution. Worked on coastal risks, marine erosion, sand dune fixation, hydraulics, forest management, botany.
33.   Maximilian Hasler, Associate Professor in Mathematics, University of French West Indies
34.   Claude Jobin, Retired A&M Engineer Specialized in Microwave Communication
35.   Alexandre Krivitzki, Psychoanalyst, Member of the International Psychoanalytical Association
36.   Roger Lainé, Retired Geological Engineer
37.   Philippe de Larminat, Professor at École Centrale de Nantes, specialist of business process modeling.
38.   René Laversanne, Former researcher at the CNRS, 16 patents.
39.   Christian Marchal, astronomer and mathematician, former research director at the French National Office for Aerospace Studies and Research, former professor at the Observatory of Paris (1980-93), former assistant professor at Polytechnic School (1981-92).
40.   Patrick Mellett, architect and CEO.
41.   Marc le Menn, Head of Metrology-Chemistry Oceanography Lab, Brest.
42.   Jacques-Marie Moranne, Retired Engineer (Ecole Centrale de Lille), Specialist in Air and Water Purification, Chemical and Nuclear Engineering
43.   Cédric Moro, geographer on natural hazards management, co-founder of Visov, an NGO in Civil defense
44.   Philippe Morvan, Engineer ENSTA and Génie Maritime, specialist in software development
45.   Charles Naville, R&D Exploration Geophysicist, IFP Energies Nouvelles
46.   Rémy Prud’homme, Emeritus Professor in Economics at University of Paris-Est, Former Deputy Director Environment, Directorate of OECD
47.   Isabelle Rivals, Associate professor in Statistics at ESPCI Paris
48.   Betrand Rouffiange, Doctor of Medicine, Specialized in Radiology
49.   Jean Rouquerol, Emeritus Research Director at CNRS Marseille, Expert in Gas Adsorption and Calorimetry
50.   François Simonet, Former Director for planning and foresight in a State Agency for water and aquatic ecosystems management.
51.   Marcel Terrier, Engineer ENSAEM in risk management, teacher at École des Mines.
52.   Étienne Vernaz, former Director of Research of CEA (Commissariat à l’Énergie Atomique) in France, Professor at INSTN (Institut National des Sciences et Techniques Nucléaires).
53.   Camille Veyres, Retired Engineer at École des Mines, Specialist in Telecommunications and Broadband Networks
54.   Brigitte Van Vliet-Lanoë, geoscientist, Emeritus Research Director (CNRS, Université de Bretagne Occidentale), stratigraphy and paleoenvironments, Quaternary and Holocene.
55.   Théa Vogt, retired CNRS searcher, géomorphology, Quaternary palaeoenvironments, soil and desertification remote sensing
56.   Henri Voron, Retired Civil Chief Engineer, Specialized in Water Management


=== SCIENTISTS AND PROFESSIONALS FROM GERMANY

1.    Fritz Vahrenholt, Professor (I.R.) am Institut für Technische und Makromolekulare Chemie der Universität Hamburg; ECD Ambassador
2.    H.J. Bandelt, Emeritus Professor of Mathematics, University of Hamburg
3.    Dietrich Bannert, Professor Honoris Causa, University of Marburg
4.    Lars Birlenbach, Dr. in Chemistry, University of Siegen
5.    Klaus Döhler, Professor of Pharma sciences, University of Hannover
6.    Friedrich-Karl Ewert, Emeritus Professor Geology, University of Paderborn
7.    Hermann Harde, Emeritus Professor of Experimental Physics and Materials Science, Helmut Schmidt-University, Hamburg
8.    Werner Kirstein, Emeritus Professor of Climatology, University of Leipzig
9.    Stefan Kröpelin, Emeritus Professor of Geology, Free University of Berlin and University of Cologne, Specialized in Climate Change of the Sahara
10.   Ulrich Kutschera, Professor of Plant Physiology &Evolutionary Biology at the University of Kassel, Germany, and Visiting Scientist in Stanford USA
11.   Horst-Joachim Lüdecke, Professor of Operations Research (i.R.) HTW of Saarland, Saarbrücken
12.   Lothar W. Meyer, Emeritus Professor of Material Engineering, Chemnitz University of Technology, Saxony Entrepreneur ‘Nordmetall GmbH’, Member of the Board of ‘Vernunftkraft Niedersachsen’
13.   Carl-Otto Weiss, Emeritus Professor in Non-linear Physics, Advisor to the European Institute for Climate and Energy, Former President of the German Meteorological Institute, Braunschweig


=== SCIENTISTS AND PROFESSIONALS FROM IRELAND

1.    Jim O’Brien, Chair, Irish Climate Science Forum, Expert Reviewer IPCC AR6, ECD Ambassador
2.    Tom Baldwin, Electrical Engineer, Specialist in Power System Security
3.    Dr Anthony D. Barry, Honorary Fellow, Irish Academy of Engineering
4.    Tony J. Carey, BA (Natural Sciences), Clare College, Cambridge
5.    David Horgan, MA (Cambridge), MBA (Harvard), Resource Company Director
6.    Seamus Hughes, BAgricSc, Specialist in Genetics
7.    Ultan Murphy, B.Sc(Hons) Chemistry, Industry Science Professional
8.    Owen O’Brien, Business Founder and Entrepreneur, MBA, DBA
9.    J. Philip O’Kane, Emeritus Professor, School of Engineering, University College Cork
10.   Peter O’Neill, Retired, School of Engineering, University College Dublin, Expert Reviewer of IPCC AR6
11.   Fintan Ryan, Retired Senior Airline Captain, Fellow Royal Aeronautical Society
12.   Dr. Brian N. Sweeney, Founding Chairman of Science Foundation Ireland
13.   Sean Tangney, Business Entrepreneur, Former Technical Director, CRH plc
14.   David Thompson, BAgricSc, MA, Animal Nutritionist
15.   Dr. Edward Walsh, Former Chairman, Irish Council for Science, Technology and Innovation; Former Director, Energy Research Group, Virginia Tech, USA


=== SCIENTISTS AND PROFESSIONALS FROM ITALY

1.    Uberto Crescenti, Professore Emerito di Geologia Applicata, Università di Chieti-Pescara, già Magnifico Rettore e Presidente della Società Geologica Italiana.
2.    Giuliano Panza, Professore di Sismologia, Università di Trieste, Accademico dei Lincei e dell’Accademia Nazionale delle Scienze, detta dei XL, vincitore nel 2018 del Premio Internazionale dell’American Geophysical Union.
3.    Alberto Prestininzi, Professore di Geologia Applicata, Università di Roma La Sapienza, già Scientific Editor in Chief della rivista internazionale Italian Journal of Engineering Geology and Environment e Direttore del Centro di Ricerca Previsione e Controllo Rischi Geologici (CERI), Sapienza Università di Roma; ED Ambassador
4.    Franco Prodi, Professore di Fisica dell’Atmosfera, Università di Ferrara.
5.    Franco Battaglia, Professore di Chimica Fisica, Università di Modena; Movimento Galileo 2001.
6.    Mario Giaccio, Professore di Tecnologia ed Economia delle Fonti di Energia, Università di Chieti-Pescara, già Preside della Facoltà di Economia.
7.    Enrico Miccadei, Professore di Geografia Fisica e Geomorfologia, Università di Chieti-Pescara.
8.    Nicola Scafetta, Professore di Fisica dell’Atmosfera e Oceanografia, Università di Napoli.
9.    Antonino Zichichi, Professore Emerito di Fisica, Università di Bologna, Fondatore e Presidente del Centro di Cultura Scientifica Ettore Majorana di Erice.
10.   Renato Angelo Ricci, Professore Emerito di Fisica, Università di Padova, già Presidente della Società Italiana di Fisica e della Società Europea di Fisica; Movimento Galileo 2001.
11.   Aurelio Misiti, Professore di Ingegneria sanitaria-Ambientale, Università di Roma La Sapienza, già Preside della Facoltà di Ingegneria, già Presidente del Consiglio Superiore ai Lavori Pubblici.
12.   Antonio Brambati, Professore di Sedimentologia, Università di Trieste, Responsabile Progetto Paleoclima-mare del PNRA, già Presidente Commissione Nazionale di Oceanografia.
13.   Cesare Barbieri, Professore Emerito di Astronomia, Università di Padova.
14.   Sergio Bartalucci, Fisico, Presidente Associazione Scienziati e Tecnologi per la Ricerca Italiana.
15.   Antonio Bianchini, Professore di Astronomia, Università di Padova.
16.   Paolo Bonifazi, Astrofisico, ex Direttore dell’Istituto di Fisica dello Spazio Interplanetario (IFSI) dell’Istituto Nazionale Astrofisica (INAF).
17.   Francesca Bozzano, Professore di Geologia Applicata, Università di Roma La Sapienza, Direttore del Centro di Ricerca Previsione, Prevenzione e Controllo Rischi Geologici (CERI).
18.   Marcello Buccolini, Professore di Geomorfologia, Università di Chieti-Pescara.
19.   Paolo Budetta, Professore di Geologia Applicata, Università di Napoli.
20.   Monia Calista, Ricercatore di Geologia Applicata, Università di Chieti-Pescara.
21.   Giovanni Carboni, Professore di Fisica, Università di Roma Tor Vergata; Movimento Galileo 2001.
22.   Franco Casali, Professore di Fisica, Università di Bologna e Accademia delle Scienze di Bologna.
23.   Giuliano Ceradelli, Ingegnere e climatologo, ALDAI.
24.   Augusta Vittoria Cerutti, membro del Comitato Glaciologico Italiano.
25.   Domenico Corradini, Professore di Geologia Storica, Università di Modena.
26.   Fulvio Crisciani, Professore di Fluidodinamica Geofisica, Università di Trieste e Istituto Scienze Marine, Cnr, Trieste.
27.   Carlo Esposito, Professore di Telerilevamento, Università di Roma La Sapienza.
28.   Antonio Mario Federico, Professore di Geotecnica, Politecnico di Bari.
29.   Mario Floris, Professore di Telerilevamento, Università di Padova.
30.   Gianni Fochi, Chimico, Scuola Normale Superiore di Pisa; giornalista scientifico.
31.   Mario Gaeta, Professore di Vulcanologia, Università di Roma La Sapienza.
32.   Giuseppe Gambolati, Fellow della American Geophysical Union, Professore di Metodi Numerici, Università di Padova.
33.   Rinaldo Genevois, Professore di Geologia Applicata, Università di Padova.
34.   Carlo Lombardi, Professore di Impianti nucleari, Politecnico di Milano.
35.   Luigi Marino, Geologo, Direttore del Centro di Ricerca Previsione, Prevenzione e Controllo Rischi Geologici (CERI)
36.   Salvatore Martino, Professore di Microzonazione sismica, Università di Roma La Sapienza.
37.   Paolo Mazzanti, Professore di Interferometria satellitare, Università di Roma La Sapienza.
38.   Adriano Mazzarella, Professore di Meteorologia e Climatologia, Università di Napoli.
39.   Carlo Merli, Professore di Tecnologie Ambientali, Università di Roma La Sapienza.
40.   Alberto Mirandola, Professore di Energetica Applicata e Presidente Dottorato di Ricerca in Energetica, Università di Padova.
41.   Renzo Mosetti, Professore di Oceanografia, Università di Trieste, già Direttore del Dipartimento di Oceanografia, Istituto OGS, Trieste.
42.   Daniela Novembre, Ricercatore in Georisorse Minerarie e Applicazioni Mineralogiche-petrografiche, Università di Chieti-Pescara.
43.   Sergio Ortolani, Professore di Astronomia e Astrofisica, Università di Padova.
44.   Antonio Pasculli, Ricercatore di Geologia Applicata, Università di Chieti-Pescara.
45.   Ernesto Pedrocchi, Professore Emerito di Energetica, Politecnico di Milano.
46.   Tommaso Piacentini, Professore di Geografia Fisica e Geomorfologia, Università di Chieti-Pescara.
47.   Guido Possa, Ingegnere nucleare, già Vice Ministro Viceministro del Ministero dell'Istruzione, Università e Ricerca, con delega alla ricerca.
48.   Mario Luigi Rainone, Professore di Geologia Applicata, Università di Chieti-V Pescara.
49.   Francesca Quercia, Geologo, Dirigente di ricerca, Ispra.
50.   Giancarlo Ruocco, Professore di Struttura della Materia, Università di Roma La Sapienza.
51.   Sergio Rusi, Professore di Idrogeologia, Università di Chieti-Pescara.
52.   Massimo Salleolini, Professore di Idrogeologia Applicata e Idrogeologia Ambientale, Università di Siena.
53.   Emanuele Scalcione, Responsabile Servizio Agrometeorologico Regionale ALSIA, Basilicata.
54.   Nicola Sciarra, Professore di Geologia Applicata, Università di Chieti-Pescara.
55.   Leonello Serva, Geologo, già Direttore Servizi Geologici d’Italia; Accademia Europa delle Scienze e delle Arti, Classe V, Scienze Tecnologiche e Ambientali; Movimento Galileo 2001.
56.   Luigi Stedile, Geologo, Centro di Ricerca Previsione, Prevenzione e Controllo Rischi Geologici (CERI), Università di Roma La Sapienza.
57.   Giorgio Trenta, Fisico e Medico, Presidente Emerito dell’Associazione Italiana di Radioprotezione Medica; Movimento Galileo 2001.
58.   Gianluca Valensise, Dirigente di Ricerca, Istituto Nazionale di Geofisica e Vulcanologia, Roma.
59.   Corrado Venturini, Professore di Geologia Strutturale, Università di Bologna.
60.   Franco Zavatti, Ricercatore di Astronomia, Università di Bologna.
61.   Achille Balduzzi, Geologo, Agip-Eni.
62.   Claudio Borri, Professore di Scienze delle Costruzioni, Università di Firenze, Coordinatore del Dottorato Internazionale in Ingegneria Civile.
63.   Pino Cippitelli, Geologo Agip-Eni.
64.   Franco Di Cesare, Dirigente, Agip-Eni.
65.   Serena Doria, Ricercatore di Probabilità e Statistica Matematica, Università di Chieti-Pescara.
66.   Enzo Siviero, Professore di Ponti, Università di Venezia, Rettore dell’Università e-Campus.
67.   Pietro Agostini, Ingegnere, Associazione Scienziati e Tecnologi per la Ricerca Italiana.
68.   Donato Barone, Ingegnere.
69.   Roberto Bonucchi, Insegnante.
70.   Gianfranco Brignoli, Geologo.
71.   Alessandro Chiaudani, Ph.D. agronomo, Università di Chieti-Pescara.
72.   Antonio Clemente, Ricercatore di Urbanistica, Università di Chieti-Pescara.
73.   Luigi Fressoia, Architetto urbanista, Perugia.
74.   Sabino Gallo, Ingegnere nucleare e scrittore scientifico.
75.   Daniela Giannessi, Primo Ricercatore, IPCF-CNR, Pisa.
76.   Roberto Grassi, Ingegnere, Amministratore G&G, Roma.
77.   Alberto Lagi, Ingegnere, Presidente di Società Ripristino Impianti Complessi Danneggiati.
78.   Luciano Lepori, Ricercatore IPCF-CNR, Pisa.
79.   Roberto Madrigali, Meteorologo.
80.   Ludovica Manusardi, Fisico nucleare e giornalista scientifico, UGIS.
81.   Maria Massullo, Tecnologa, ENEA-Casaccia, Roma.
82.   Enrico Matteoli, Primo Ricercatore, IPCF-CNR, Pisa.
83.   Gabriella Mincione, Professore di Scienze e Tecniche di Medicina di Laboratorio, Università di Chieti-Pescara.
84.   Massimo Pallotta, Primo Tecnologo, Istituto Nazionale Fisica Nucleare.
85.   Enzo Pennetta, Professore di Scienze Naturali e divulgatore scientifico.
86.   Franco Puglia, Ingegnere, Presidente CCC, Milano.
87.   Nunzia Radatti, Chimico, Sogin.
88.   Vincenzo Romanello, Ingegnere nucleare, Ricercatore presso il Centro Ricerca di Rez, Repubblica Ceca.
89.   Alberto Rota, Ingegnere, Ricercatore presso CISE e ENEL ed esperto di energie rinnovabili.
90.   Massimo Sepielli, Direttore di Ricerca, ENEA, Roma.
91.   Ugo Spezia, Ingegnere, Responsabile Sicurezza Industriale, SoGIN; Movimento Galileo 2001.
92.   Emilio Stefani, Professore di Patologia vegetale, Università di Modena.
93.   Umberto Tirelli, Visiting Senior Scientist, Istituto Tumori d’Aviano; Movimento Galileo 2001.
94.   Roberto Vacca, Ingegnere e scrittore scientifico.
95.   Giorgio Bertucelli, Ingegnere, già Dirigente Industriale, Associazione Lombarda Dirigenti Aziende Industriali.
96.   Luciano Biasini, Professore Emerito, già Docente di Calcoli numerici e grafici, Direttore dell'Istituto Matematico e Preside della Facoltà di Scienze Matematiche, Fisiche e Naturali dell'Università di Ferrara.
97.   Giampiero Borrielli, Ingegnere.
98.   Antonio Maria Calabrò, Ingegnere, Ricercatore, Consulente.
99.   Enrico Colombo, Chimico, Dirigente Industriale.
100. Stefano De Pieri, Ingegnere energetico e nucleare.
101. Benedetto De Vivo, Professore di Geochimica in pensione dall’Università di Napoli; ora Professore Straordinario presso Università Telematica Pegaso, Napoli.
102. Carlo Del Corso, Ingegnere Chimico.
103. Francesco Dellacasa, Ingegnere, amministratore di società nel settore energetico.
104. Sergio Fontanot, Ingegnere.
105. Umberto Gentili, Fisico dell'ENEA, Climatologo per il Progetto Antartide.
106. Ettore Malpezzi, Ingegnere.
107. Alessandro Martelli, Ingegnere, già dirigente ENEA.
108. Umberto Minopoli, Presidente dell'Associazione Italiana Nucleare.
109. Antonio Panebianco, Ingegnere.
110. Giorgio Prinzi, Ingegnere, Direttore responsabile della rivista 21mo Secolo Scienza e tecnologi
111. Arnaldo Radovix, Geologo, Risk Manager in derivati finanziari.
112. Mario Rampichini, Chimico, Dirigente Industriale in pensione, Consulente.
113. Marco Ricci, Fisico, Primo Ricercatore, Istituto Nazionale di Fisica


=== SCIENTISTS AND PROFESSIONALS FROM THE NETHERLANDS

1.    Guus Berkhout, Emeritus Professor of Geophysics, Delft University of Technology, Member of the Royal Netherlands Academy of Arts and Sciences; ECD Ambassador
2.    Maarten van Andel, Author of the ‘Groene Illusie’
3.    André Bijkerk, Geophysicist, Former Royal Dutch Airforce, now Climate Researcher
4.    Peter Bloemers, Emeritus Professor of biochemistry, Radbout University, Nijmegen
5.    Paul M.C. Braat, Emeritus Professor of Pulmonary Physics, University of Amsterdam
6.    Solke Bruin, Emeritus Professor of Product-driven Process Technology, University of Eindhoven, and Former member Management Committee Unilever Research, Vlaardingen
7.    Paul Cliteur, Professor of Legal Sciences, Member of the Senate of The Netherlands
8.    Albert J.H.G. Cloosterman, Retired Chemical Engineer, Publicist on Climate and Cosmological Matters
9.    Marcel Crok, Climate Researcher and Science Journalist
10.   David E. Dirkse, Former Computer Engineer and Teacher Mathematics
11.   Kees de Groot, Former Director Upstream Research Lab. Shell
12.   Kees de Lange, Emeritus Professor of Physics, Vrije University Amsterdam and University of Amsterdam
13.   Louw Feenstra, Emeritus Professor Erasmus University and philosopher, Rotterdam
14.   Frans H. Gortemaker, Former Vice president Unilever Global R&D
15.   Leo Halvers, Former Director Biliton Research Arnhem and former Director technology Foundation STW
16.   Eduard Harinck, Former Logistics Expert, Nedlloyd Group/KPMG consulting; member of the ED support team
17.   J.R. Hetzler, Forestry Economics and Time Series Modeling
18.   Jan F. Holtrop, Emeritus Professor of Petroleum Engineering, Delft University of Technology
19.   A. Huijser, Physicist and Former CTO Royal Philips Electronics
20.   W. J. (Wouter) Keller, Emeritus Professor of Statistical Methods, Former Member Board of Directors, Central Bureau of Statistics (CBS)
21.   Jacques van Kerchove, Economist and Marketeer, Former CFO Rabobank, now Climate and Environment researcher
22.   R.W.J. Kouffeld, Emeritus Professor of Energy Conversion, Delft University of Technology
23.   Hans H.J. Labohm, Former Expert Reviewer IPCC
24.   Kees le Pair, Physicist, Former Director of Research organisations FOM and Technology & former member of the General Energy Council, The Netherlands
25.   B.G. Linsen, Former Director Unilever Research Vlaardingen, The Netherlands
26.   Pieter Lukkes, Emeritus Professor of Economic and Human Geography, University of Groningen
27.   Hugo Matthijssen, Former Teacher Meteorology, now Publicist on Climate Matters
28.   Simon Middelhoek, Emeritus Professor of Electronic Instrumentation and Sensors, Delft University of Technology, Member of the Royal Netherlands Academy of Arts and Sciences and Member of the National Academy of Engineering, USA
29.   J.M. Mulderink, Former General Director Akzo-Nobel
30.   Rob Nijssen, Radar Engineer and Publicist on Climate Matters
31.   Leffert Oldenkamp, Expert Forest Management
32.   Peter Oosterling, Former Scientist E & P Shell, now active as Climate Researcher; member of the ED support team
33.   Kees Pieters, Mathematician; Former Operational Research and ICT manager at Shell
34.   Reynier Pronk, Former IT Manager, Accredited Project Management Consultant and Trainer
35.   G.T. Robillard, Emeritus Professor of Biochemistry and Biophysics
36.   Arthur Rörsch, Former Member Board of Directors, TNO, The Netherlands
37.   Don Schäfer, Former Director Shell Exploration & Production and New Business, Shell
38.   Frans Schrijver, Strategy Consultant and Climate Publicist
39.   Jos de Smit. Emeritus Professor of Stochastic Operations Research and Former Rector Magnificus of the University of Twente
40.   Albert Stienstra, Emeritus Professor of Computer Simulation and Micro-Electronics, Delft University of Technology
41.   P.J. Strijkert, Former Member Board of Directors of DSM, Delft, The Netherlands
42.   Dick Thoenes, Emeritus Professor of Chemical Technology, Technical University of Eindhoven
43.   Fred Udo, Emeritus Professor of Nuclear Physics, Vrije Universiteit Brussels, Belgium
44.   J.F. van de Vate, Former Director ECN, Petten, The Netherlands. Former UN Delegate IPCC.
45.   Frans van den Beemt, Nuclear Physicist, Former Program Director Technology Foundation STW
46.   Rutger van Santen, Emeritus Professor of Anorganic Chemistry and Catalysis, Former Rector Magnificus, Eindhoven University
47.   Barend-Jan Smits, Geologist, Former Director of Wintershall Nederland, BASF Group
48.   Hans van Suijdam, Former Executive Vice President Research and Development DSM, The Netherlands
49.   Peter van Toorn, Former Research Geophysicist Shell
50.   Jannes J. Verwer, Former CEO Large Electricity Generation Group and Former Chairman Supervisory Board State Owned Radio Active Waste Storage Facilities, The Netherlands
51.   Henk van der Vorst, Emeritus Professor of Numerical Mathematics, University of Utrecht
52.   Jaap van der Vuurst de Vries, Emeritus Professor of Petroleum Engineering, Former Dean Faculty of Applied Earth Sciences, Delft University of Technology
53.   Karel Wakker, Emeritus Professor of Astrodynamics & Geodynamics, Delft University of Technology
54.   Cyril Wentzel, Multi-Physics Engineer and Chairman of Environmental Think Tank ‘Groene Rekenkamer’
55.   Dolf van Wijk, Formerly AkzoNobel Environmental Research Laboratory and Former Executive Director Cefic-Euro Chlor, Brussels
56.   W.J. Witteman, Professor of Applied Physics and CO2 lasers, University of Twente
57.   Theo Wolters, Co-founder ‘Groene Rekenkamer’ and ‘Climategate.nl’


=== SCIENTISTS AND PROFESSIONALS FROM NORWAY

1.    Morten Jødal, Biologist, Former Employee of the Norwegian Research Council and the Centre for the Development and Environment at the University of Oslo; ECD Ambassador
2.    Gunnar Abrahamsen, Professor Em. Soil Science, University of Life Sciences, Norway 3.    Stein Storlie Bergsmark, Phycisist, Former head of renewable Energy Studies Programmes, University of Agder, Norway
4.    Reidar Borgstrøm, Professor Emeritus in fishbiology and Nature Conservation, University of Life Sciences Norway
5.    Jon Gulbrandsen, PhD, biologist, Associate Professor NOFIMA and NOAA (USA), Norway
6.    Rögnvaldur Hannesson, Professor Emeritus, Norwegian School of Economics, Norway
7.    Geir Hasnes, Adjunct Associate Professor, Institute of applied Cybernetics, Norwegian University of Science and Technology, Norway
8.    Hans Konrad Johnsen, Dr. Ing., Norway
9.    Arnfinn Langeland, Professor Emeritus Biology, Norwegian University of Science and Technology
10.   Willy Nerdal, professor of Chemistry, University of Bergen
11.   Ulf Torgny Rock, Master of Chemical Engineering, Norsk Hydro, Norway
12.   Martin Torvald Hovland, Geophysical and Geological Advisor, Former Lecturer at University of Tromsø
13.   Elen Roaldset, Emertitus Professor in Geology, University of Oslo, Former Director of Natural History Museum Oslo, Professor at Norwegian University of Science and Technology
14.   Hakon Gunnar Rueslatten, Geological Researcher, Trondhheim
15.   Tom V Segalstad, Associate Professor Emeritus of Geochemistry, University of Oslo, Norway
16.   Jan-Erik Solheim, Professor Emeritus Astrophysics, University of Oslo
17.   Jørgen Stenersen, Professor Emeritus Eco-Toxicology, University of Oslo


=== SCIENTISTS AND PROFESSIONALS FROM POLAND

1.    Marek Boinski, Chairman of the National Section of Energy Workers’ Union NSZZ
2.    Jaroslaw Grzesik, Chairman of the National Secretariat of Mine and Energy Workers’ Union NSZZ
3.    Dominik Kolorz, Chairman of the Slasko-Dabrowski Region of NSZZ


=== SCIENTISTS AND PROFESSIONALS FROM SWEDEN

1.    Ingemar Nordin, Emeritus Professor Philosophy of Science, Linköping University; ECD Ambassador
2.    Sture Åström, Professional in cCimate Issues, Secretary of the Swedish Network Klimatsans
3.    Rolf Bergman, Emeritus Professor of Physical Chemistry, Uppsala University
4.    Dr. Lars Bern, Member of The Royal Swedish Academy of Sciences, Retired CEO in Incentive AB
5.    Magnus Cederlöf, Software Specialist, Stockholm
6.    Per-Olof Eriksson, Physicist, Former CEO of Sandvik Group
7.    Dr. Anders Flodin, Business Development Manager, Höganäs AB in North Carolina
8.    David D. Gee, Professor Em Orogen Dynamics, Uppsala University, Sweden
9.    Hans Jelbring, Climate researcher
10.   Claes Johnson, Emeritus Professor of Mathematics at Royal Institute of Technology, Stockholm
11.   Gunnar Juliusson, Professor of Hematology, Lund University, Senior Consultant, Skåne, University Hospital, Lund
12.   Sten Kaijser, Emeritus Professor of Mathematics, Uppsala University
13.   Johan Montelius, Associate Professor of Computer Science at the Royal Institute of Technology, Stockholm
14.   Nils-Axel Mörner, Emeritus Professor Geology, President of the Independent Committee on Geoethics. Former head of Paleogeophysics & Geodynamics at Stockholm University
15.   Gösta Pettersson, Emeritus Professor in Biochemistry, University of Lund
16.   Marian Radetzki, Emeritus Professor of Economics, Luleå University of Technology
17.   Peter Stilbs, Emeritus Professor of Physical Chemistry, Royal Institute of Technology (KTH), Stockholm
18.   Elsa Widding, Consultant, Author on Climate Change, Stockholm


=== SCIENTISTS AND PROFESSIONALS FROM SWITZERLAND

1.    Jean-Claude Pont, Dr. Math., Emeritus Professor of The History of Philosophy of Sciences, University of Genève
2     Jef Ongena, Member of the Permanent Monitoring Panel for World Energy, World Federation of Scientists, Geneva


=== SCIENTISTS AND PROFESSIONALS FROM UNITED KINGDOM

1.    Christopher Monckton of Brenchley, Peer of the Realm and author of several reviewed papers on climate; ECD Ambassador
2.    David Bodecott, Consultant Geophysics and Geology, Fellow of the Geological Society of London
3.    D. Q. Bowen, Emeritus Professor of Earth and Ocean Sciences, Fellow International Union for Quaternary Research, Cardiff University
4.    Michael Brown, Expert in large scale thermal fluid dynamic models.
5.    John C. W. Cope, Professor of Natural Sciences, National Museum Wales, Cardiff
6.    Richard Courtney, Retired Material Scientist, Expert Peer Reviewer of the IPCC
7.    Isabel Davis, Geophysicist and Entrepreneur
8.    Howard Dewhirst FGS, Geologist, Initiator Open Letter to the Geological Society of London
9.    Gregor Dixon FGS, Geologist, former member Geological Society of London
10.   Roderick Paul Eaton, Retired Energy Systems Analyst from the UK Electricity Supply Industry
11.   Peter Gill, Physicist, Former Chair of the Institute of Physics Energy Group, UK
12.   Gil Gilchrist, Geophysicist, UK
13.   Tim Harper FGS, Geologist, Entrepreneur, Devon
14.   Bob Heath, retired Geophysicist, Honorary member of the Indian Society of Petroleum Geologists
15.   David A. L. Jenkins, Geologist, Director Hurricane Energy plc
16.   Chris Matchatte-Downes, Geologist, fellow of the geological Society of Gt Britain
17.   Edward Nealon, Geologist Member of the Australian Institute of Mining & Metallurgy, UK
18.   Peter Owen FGS, Fellow of the Geological Society of London
19.   Clive Randle, Geologist, Fellow of the Geological Society of London
20.   Michael F. Ridd, Geologist, Fellow of the Geological Society of London
21.   Michael Seymour, geologist, Former Managing Director Aurelian Oil & Gas and Trajan Oil limited
22.   Valentina Zharkova, Professor of Mathematics and Astrophysics, Northumbria University, Newcastle upon Tyne


== SCIENTISTS FROM OUTSIDE THE EU

=== SCIENTISTS AND PROFESSIONALS FROM AUSTRALIA

1.    Viv Forbes, Geologist with Special Interest in Climate, Founder of www. carbon-sense. com, Queensland, Australia; ECD Ambassador
2.    Don Andersen,
3.    David Archibald, Research Scientist, Australia
4.    Michael Asten, Emeritus Professor in Geophysics and Continuing Senior Research Fellow at the Monash University, Melbourne
5.    Jeremy Barlow, Energy and Mining professional, Director and CEO, Australia
6.    Colin Barton, Geologist, Former Principal Research Scientist CSIRO, Australia
7.    Gordon Batt, Director GCB Investments Pty Ltd
8.    Robert M. Bell, Retired geologist, Victoria, Australia
9.    Richard Blayden Professional Engineer
10.   Howard Thomas Brady, Member Explorers Club of New York, Member of the Australian Academy of Forensic Sciences
11.   Geoff Brown, Organizer of a Critical Climate Group, Australia
12.   Douglas Buerger, Fellow Australasian Institute of Mining and Metallurgy, member of Australian Institute of Company Directors, Australia
13.   Mike Bugler, Retired Environmental Consultant, Australia
14.   Ray Carman, Organic chemist, Honorary Fellow University of Queensland, Australia
15.   Peter Champness, Radiologist, Australia
16.   Andrew E. Chapman, Expert on Rainfall and flood events, Australia
17.   Richard Corbett, Member Royal Australian Chemical Institute, Member of The Clean Air Society of Australia and New Zealand
18.   Majorie Curtis, Retired Geologist, Stratigrapher and Palaeoclimatic Studies, Canberra, Australia
19.   Geoff Derrick, Geologist
20.   Aert Driessen, Geologist, Fellow Australian Institute of Geoscientists, Australia
21.   John A. Earthrowl, retired Geologist, Brisbane Australia
22.   Jeremy K. Ellis, Retired Chairman of BHP, now Chairman of the Saltbush Club, Australia
23.   Matthew J. Fagan, Founder and President of FastCAM Inc.
24.   Rodney Fripp, former lecturer in geology, geochemistry and geotechtonics
25.   Christopher J.S. Game, Retired Neurophysiologist, Australia
26.   Robin George, Geologist, Canterbury, Australia
27.   David Gibson, Experimental Physicist, Australia
28.   Gavin Gillman, Former Senior Principal Research Scientist with SCIRO Australia; Founding Director of the IITA Ecoregional Research Centre in Cameroon for the International Institute for Tropical Agriculture (IITA)
29.   Hamish Grant, MR Spectroscopy & Imaging Consultant, Victoria, Australia
30.   Lindsay Hackett, Founding member of the Saltbush Club in Australia
31.   Erl Happ, Managing Director, Australia
32.   John Happs, Geoscientist, Retired University Lecturer, Australia
33.   John Harrison, Retired Marine Engineer, Australia
34.   Jarvis Hayman, Visiting Fellow School of Archaeology & Anthropology, Australian National University
35.   Mark Henschke, Retired geologist in mining, oil and gas, Australia
36.   Gerhard Hofmann, Geologist and Palaeontologist, former Director of the Geological Survey of Queensland
37.   Geraint Hughes, Mechanical Building Engineer, Climate Researcher, Australia
38.   Kevin Kemmis, Expert in Information Technology, Climate Researcher
39.   Hugh H. Laird, Retired Tropical Agriculture Executive
40.   John Leisten OBE, expert in physical chemistry
41.   Brian Levitan, worked for NASA, now Technology Consultant to multinationals
42.   Matthew David Linn, Fellow of the Institution of Engineers of Australia
43.   Gerard McGann, Technical Director Eon NRG
44.   Rodney McKellar, Retired Geologist, Queensland, Australia
45.   John McLean, Author of first major review of HadCRUT 4 climate temperature data, Member of New Zealand Climate Science Coalition
46.   Ross McLeod, Retired Environmental Health Officer, Australia
47.   Finlay MacRitchie, Professor Emeritus in the Department of Grain Science and Industry at Kansas State University, USA. Australia
48.   John Michelmore, Retired Industrial Chemist, South Australia
49.   Alan Moran, Contributor and Editor of the Mark Steyn Compilation: “Climate Change, the Facts”, Author of Climate Change: “Treaties and Policies in the Trump Era”
50.   Des Moore, Former Deputy Secretary of the Federal Treasury, founder and leader of the Institute for Private Enterprise
51.   Hugh Morgan, prominent Australian mining executive, Fellow of the Australian Academy of Technology, Science and Engineering (FTSE).
52.   C.D. Ollier, Emeritus Professor of Geology and Honorary Research Fellow at the School of Earth and Geographical Sciences, University of Western Australia
53.   Ian Plimer, Emeritus Professor of Mining Geology at University of Adelaide and Author of ‘Climate Delusion and the Great Electricity Rip-off’
54.   Alistair Pope, psc, CM, Sceptical Scientific Contrarian in the Climate Debate
55.   Tom Quirk, Nuclear Physicist, Australia
56.   Campbell Rankine, Varrister and Solicitor, Australia
57.   Peter Ridd, Oceanographer and Geophysicist, Former Head of Physics at the James Cook University, Queensland
58.   Nigel Rowlands, retired from mining and exploration industry
59.   Judy Ryan, Editor Principia Scientific Institution-Australia
60.   Jim Simpson, Retired from Managing Positions in different International Telecommunications Firms, now active in the Australian Climate Community,
61.   Case Smit, Physicist, Expert in Environmental Protection, Co-founder of the Galileo Movement, Australia
62.   Lee Smith, University Lecturer in Spatial Technology, Responsible for State Government Precise Monitoring of Sea Level and International Sea Boundaries
63.   Darren Speirs, Independent Business Owner, Rangeland NRM Consultants, Australia
64.   Geoffrey Stocker, Professor and Head of Department of Forestry, PNG University of Technology – Director of PNG Forest Research Institute
65.   Rodney R. Stuart, Retired expert in energy industry, Tasmania, Australia
66.   R. Symons, Professional Engineer, Expert in Temperature Control of Industrial Buildings
67.   Rustyn Wesley Thomas, Retired aircraft engineer, Australia
68.   John W. Turner, Science Educator, Noosa Heads, Australia
69.   Peter Tyrer, Project Controls Engineer in mining industry, Australia
70.   Terrence Vincent, Security Engineer, Small Business Adviser AIST, ASIAL, SMBE, Australia
71.   James Walter, Medical doctor, Australia
72.   John Warnock, Astro Economist, Australia
73.   Christopher Kenneth Warren, Expert in hydroelectric dam design and construction, Australia
74.   Neil Wilkins, Retired geologist, Australia
75.   P.C. Wilson, Former journalist with the A.B.C. Queensland, Australia


=== SCIENTISTS AND PROFESSIONALS FROM BRAZIL

1.    Luiz Carlos Baldicero Molion, Emeritus Professor of the Federal University of Alagoas (UFAL), Formerly of the National Institute of Space research (INPE)
2.    Ricardo Augusto Felicio, Professor of the Department of Geography of the University of Sao Paulo (USP), Member of the Brazilian Society of Meteorology (SBMET)
3.    Geraldo Luis Saraiva Lino, Geologist, Author of ‘How a natural Phenomenon Was Converted into a False Global Emergency
4.    Dr. Thiago Maia, Nuclear Physicist with PhD in Astrophysics, wrote critical climate letter to Brazilian Government
5.    Igor Vaz maquieira, Biologist, Specialist in Environmental Management
6.    Mario de Carvalho Fontes Neto, Agronomist, Editor of ‘The Great Global Warming Swindle’
7.    Daniela de Souza Onca, Professor of the Geography Department of the State University of Santa Catarina (UDESC)


=== SCIENTISTS AND PROFESSIONALS FROM CANADA

1.    Jeffrey Ernest Foss, Professor of Philosophy of Science, University of Victoria, English Canada; ECD Ambassador
2.    Reynald Du Berger, Emeritus Professor of Geophysics at the L’Université du Québec a Chicoutimi, French Canada, ECD Ambassador
3.    Alain Bonnier, Physicist, INRS-Centre de Recherche and Energy Montréal, Canada
4.    Ian Clark, Professor of Earth and Environmental Sciences, University of Ottawa
5.    Susan Crockford, Zoologist and Polar Bear Expert, Former Adjunct Professor University of Victoria, Canada
6.    Paul A. Johnston, Associate Professor, Department of Earth and Environmental Sciences, Mount Royal University, Calgary, Alberta
7.    Klaus L.E. Kaiser, Retired Research Scientist, National Water Research Institute, Author of Numerous Press Articles, Canada
8.    Madhav Khandekar, Expert Reviewer IPCC 2007 AR4 Cycle, Canada
9.    Kees van Kooten, Professor of Economics and Canada Research Chair in Environmental Studies and Climate, University of Victoria, Canada
10.   Allen MacRae, retired Engineer, Canada
11.   Paul MacRae, Independent Climate Researcher, Canada
12.   Patrick Moore, Ecologist, Chair CO2 Coalition, Co-Founder Green Peace, Canada
13.   Brian R. Pratt, Professor of Geological Sciences, University of Saskatchewan
14.   Peter Salonius, Retired Research Scientist, Natural Resources, Canada
15.   Marcelo C. Santos, professor of Geodesy, University of New Brunswick, Canada
16.   Ian Semple, Retired Geologist, of McGill University, Canada
17.   William van Wijngaarden, Professor of Physics, York University, Canada


=== SCIENTISTS AND PROFESSIONALS FROM CHINA AND HONG KONG

1.    NG Young, Principal Geoscientist, Danxiashan Global Geopark of China
2.    Wyss Yim, Retired Professor, Department of Earth Sciences, The University of Hong Kong, Hong Kong SAR, China / Deputy Chairman, Climate Change Science Implementation Team, UNESCO International Year for Planet Earth 2007-2009 / Expert Reviewer IPCC AR2


=== SCIENTISTS AND PROFESSIONALS FROM INDIA

1.    Sanjeev Sabhlok, Economist with focus on climate and energy policy, India


=== SCIENTISTS AND PROFESSIONALS FROM JAPAN

1.    Masayuki Hyodo, Professor of Earth Science, Kobe University, Japan


=== SCIENTISTS AND PROFESSIONALS FROM NEW ZEALAND

1.    Terry Dunleavy MBE, co-founder (2006) and honorary secretary, New Zealand Climate Science Coalition; ECD Ambassador
2.    Deborah Alexander, Agricultural Scientist, New Zealand
3.    Jock Allison, retired Agricultural Scientist, Ministry of Agriculture,New-Zealand
4.    Barry Brill , OBE, Previously Minister of Science and Techology, New Zealand
5.    Doug Edmeades, Managing Director agKnowledge Ltd., New Zealand
6.    Roger High Dewhurst, Retired, geologist/hydrogeologist, New Zealand
7.    Geoffrey G. Duffy, Professor Emeritus, University of Auckland, New Zealand
8.    Joe Fone, CAD Engineer, Enatel Ltd
9.    Bryan Leyland, Power Systems Engineer and Experienced Renewable Energy Specialist
10.   Gerrit J. van der Lingen, Paleoclimatologist, New Zealand, Author of the Book The Fable of Stable Climate
11.   John Scarry ME (Civil), structural engineer, member of the New Zealand Climate Science Coalition
12.   John Sexton, Member of the New Zealand Climate Coalition
13.   Philip Strong, Science Research Leader & Member of the New Zealand Climate Coalition
14.   Richard Treadgold, Executive Member NZ Climate Scienc Coalition, Convenor Climate Conversation Group


=== SCIENTISTS AND PROFESSIONALS FROM RUSSIAN FEDERATION

1     Habibullo Abdussamatov, Head of the Space Research Sector of the Sun, Pulkova Observatory RAS and Head of the Lunar Observatory Project on Monitoring of the Climate, Russian Federation


=== SCIENTISTS AND PROFESSIONALS FROM SOUTH-AFRICA

1.    Rosemary Falcon, Emeritus Professor Clean Coal Technology Research Group at the University of Witwatersrand, Director Fossil Fuel Foundation
2.    John Ledger, Visiting Professor at the University of the Witwatersrand, Energy and Environmental Consultant
3.    Don Mingay, Retired Professor of Nuclear Physics, South Africa


=== SCIENTISTS AND PROFESSIONALS FROM USA

1.    Richard Lindzen, Emeritus Professor Atmospheres, Oceans and Climate, MIT, USA; ECD Ambassador
2.    Ralph B. Alexander, Emeritus Professor of Physics, Science Writer
3.    Anthony J. Armini, Retired Founder and CEO Implant Sciences Corp.., USA
4.    Tim Ball, Emeritus Professor Geography, University of Winnipeg, Canada and Advisor of the International Science Coalition
5.    Hans-Peter Bär, Emeritus Professor of Pharmacology, Canada and Former Dean of Basic Medical Sciences, American University of Barbados, Barbados
6.    James R. Barrante, Emeritus Professor of Physical Chemistry, USA
7.    Charles G. Battig, Climate Adviser, Heartland Institute, USA
8.    Larry Bell, Endowed Professor of Space Architecture, University of Houston, USA
9.    Elliott D. Bloom, Emeritus Professor of Particle Physics and Astrophysics, KIPAC-SLAG, Stanford University
10.   Daniel Botkin, Emeritus Professor of Biology, Climate Researcher, Author of the Book: Twenty-five Myths That Are Destroying the Environment, USA
11.   Martin Cornell, Retired Senior Scientist, Dow Chemical Company, USA
12.   Joseph S. D’aleo, Professor of Meteorology and Climatology at Lyndon Stage College, Founder of Icecap.us, First Director of meteorology of the Weather Channel, USA
13.   David Deming, Professor of Arts & Sciences, University of Oklahoma, USA
14.   Harold H. Doiron, Retired NASA Engineer, USA
15.   John Droz jr, Physicist, Founder of AWED Alliance, USA
16.   Freeman Dyson, Emeritus Professor Natural Sciences, Institute of Advanced Study, Princeton University, USA
17.   Peter Farrell, Fellow of the US National Academy of Engineering, USA
18.   Rex Fleming, Research Scientist, Author of Book on Carbon Dioxide Fallacy, Retired President Global Aerospace, USA
19.   Gordon J. Fulks, Astrophysicist, Board of Directors CO2 Coalition, Co-founder Global Warming Realists
20.   Terry Gannon, Physicist, Retired Semiconductor Executive, USA
21.   Ulrich H. Gerlach, Professor of Mathematics, Ohio State University, USA
22.   Laurence I. Gould, Professor of Physics, University of Hartford, Past Chair, New England Section of the American Physical Society.
23.   Steve Goreham, Executive Director, Climate Science Coalition of America, USA
24.   David Heald, Retired Electrical Engineer, USA
25.   Howard C. Hayden, Emeritus Professor of Physics, University of Connecticut, USA
26.   Wayne P. Kraus, Member American Institute of Chemical Engineers (AIChE)
27.   Patrick J. Michaels, Competitive Enterprise Institute, Washington DC, USA
28.   Pamela Matlack-Klein, Member of Portuguese Sea Level Project, USA
29.   Richard McFarland, Retired NASA Physicist, USA
30.   Daniel W. Nebert, Professor Emeritus, Department of Environmental Medicine and Center for Environmental Genetics, University of Cincinnati
31.   Thomas O’Connor, Member American Association of Petroleum Geologists, Washington, USA
32.   Herman A. Pope, retired Aerospace Engineer NASA-JSC, USA
33.   Willem Post, Independent Researcher regarding Energy and Environment
34.   Phil Robinson, Retired Chemist in the Aluminium and Steel Industry
35.   Willie Soon, Independent Scientist, USA
36.   Ronald Stein, Professional Engineer, USA
37.   Paul Taylor, Energy Economist, recipient Rossitor Raymond Award, Golden Colorado, USA
38.   Richard Trzupek, Chemist and Air Quality Expert
39.   Waheed Uddin, Professor of Engineering Science, University of Mississippi, Expert in Climate Modeling, Former Advisor UN
40.   William B. Walters, Guggenheim Fellow, Professor of Atmospheric, Nuclear and Environmental Chemistry, University of Maryland, USA
41.   Steven E. Weismantel, Retired Engineer and Climate Researcher, USA
42.   Gregory R. Wrightstone, Expert Reviewer IPCCC 6th Assessment Report (AR6), USA
43.   David Wojick, Cognitive Scientist, USA
44.   Thomas Wysmuller, Retired NASA Executive, USA
45.   Bob Zybach, Program Manager, Oregon Websites and Watersheds Project INC., USA
